joy:
  ros__parameters:
    device_name: "DualSense Wireless Controller"
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    # Este modo 'default' no se usa porque siempre se mantiene presionado L1.
    # Se puede dejar como está, no afecta.
    default:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 0.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.0
          offset: 0.0

    # Esta es ahora la ÚNICA sección de control activa.
    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: teleop
      # Requiere mantener presionado L1 (botón 4) para conducir manualmente.
      deadman_buttons: [4]
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 5.0  # Ajusta la velocidad máxima manual aquí
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.34 # Ajusta la sensibilidad de la dirección aquí
          offset: 0.0
