# Contenido COMPLETO y CORRECTO para joy_teleop.yaml

joy:
  ros__parameters:
    device_name: "DualSense Wireless Controller"
    device_id: 0
    deadzone: 0.01
    autorepeat_rate: 20.0
    coalesce_interval: 0.01

joy_teleop:
  ros__parameters:
    # Perfil para el control manual
    human_control:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: /teleop
      deadman_buttons: [4]  # Botón L1
      axis_mappings:
        drive-speed:
          axis: 1
          scale: 5.0
          offset: 0.0
        drive-steering_angle:
          axis: 2
          scale: 0.34
          offset: 0.0

    # Perfil para la PARADA DE EMERGENCIA
    emergency_stop:
      type: topic
      interface_type: ackermann_msgs/msg/AckermannDriveStamped
      topic_name: /emergency_stop
      deadman_buttons: [1]  # Botón 'X' (índice 1)
      axis_mappings:
        # Forzamos la velocidad y el giro a cero
        drive-speed: { axis: 1, scale: 0.0, offset: 0.0 }
        drive-steering_angle: { axis: 2, scale: 0.0, offset: 0.0 }