# Parámetros para el nodo Odom Pure Pursuit
rpp_follower:
  ros__parameters:
    # --- Topics y Configuración Base ---
    # CAMBIO CRÍTICO: Apuntamos de nuevo a la odometría del VESC
    topic_odom: "/odom"
    
    # El resto es igual
    wheelbase: 0.33
    path_frame: "odom" # Usamos el frame 'odom' para visualizar, ya que no hay 'map'
    odom_timeout: 1.0  # Un timeout corto es suficiente con odom
    
    # --- Parámetros de Pure Pursuit ---
    loop_track: True
    LOOKAHEAD_DIST: 2.5
    v_cmd: 2.0
    steer_limit: 0.41

    # --- Parámetros de Obstacle Avoidance (LIDAR) ---
    use_scan: True
    scan_topic: "/scan"
    avoid_enabled: True
    danger_dist: 1.5
    sector_deg: 120.0
    gap_margin: 0.15
    gap_mix_alpha: 0.7
     
    # --- Parámetros de Visualización (puedes dejarlos así) ---
    publish_markers: True
    publish_avoid_markers: True
    publish_actual_path: True
    actual_path_len: 4000
    actual_path_frame: "map" # Publicar la ruta real en el frame del mapa
