# Parámetros para el nodo Reactive Pure Pursuit
rpp_follower:
  ros__parameters:
    # --- Topics y Configuración Base ---
    # El topic de odometría del coche real (no de la simulación)
    topic_odom: "/odom"
    # El topic de comandos será redirigido en el launch, no necesita valor aquí
    topic_cmd: "/autonomous"
    
    # --- NUEVO: Configuración de Localización AMCL ---
    use_amcl: true                    # Activar fusión AMCL + Odometría
    topic_amcl: "/amcl_pose"          # Topic donde AMCL publica la pose corregida
    amcl_timeout: 5.0                 # Segundos sin AMCL antes de usar odometría como fallback
    amcl_priority: true               # true = Priorizar AMCL cuando está disponible
                                      # false = Priorizar odometría, AMCL solo como fallback
    
    # --- Parámetros de Pure Pursuit ---
    # El wheelbase del F1TENTH
    wheelbase: 0.33
    # Frame del mapa para las visualizaciones
    path_frame: "map"
    odom_timeout: 5.0
    loop_track: true
    
    # AJUSTADO: Lookahead más corto para curvas más cerradas
    LOOKAHEAD_DIST: 0.8               # Reducido de 2.5 a 1.5 para giros más agresivos
    
    v_cmd: 1.5                        # Velocidad para el coche real, ajusta según la pista
    
    # AJUSTADO: Límite de dirección aumentado para girar más
    steer_limit: 0.41                 # Aumentado de 0.41 (23.5°) a 0.50 (28.6°)
    
    ramp_rate: 2.0                    # Aceleración suave (m/s²)
    rate_hz: 50.0                     # Frecuencia de control
        
    # --- Parámetros de conteo de vueltas ---
    min_lap_time_s: 5.0               # Tiempo mínimo de vuelta para evitar false positives
    cross_hi_frac: 0.75               # Fracción superior para detectar cruce de meta
    cross_lo_frac: 0.25               # Fracción inferior para detectar cruce de meta
    local_path_len: 80                # Número de waypoints a mostrar en el path local
    
    # --- Parámetros de Obstacle Avoidance (LIDAR) ---
    use_scan: true
    scan_topic: "/scan"
    avoid_enabled: false
    
    # AJUSTADO: Parámetros de evasión para tu caso
    danger_dist: 1.5                  # Distancia a la que se activa la evasión (metros)
    sector_deg: 120.0                 # Sector frontal a analizar (±60°)
    min_gap_deg: 8.0                  # Ancho mínimo de gap para ser considerado válido
    gap_margin: 0.15                  # Margen extra de seguridad en gaps (metros)
    gap_mix_alpha: 0.7                # Balance: 0.7=70% gap, 30% waypoint
                                      # Aumenta para evasión más agresiva (0.8-0.9)
                                      # Reduce para seguir más el path (0.5-0.6)
    
    # --- Parámetros de Visualización ---
    publish_markers: true             # Publicar waypoints en RViz
    publish_avoid_markers: true       # Publicar marcador de evasión
    publish_actual_path: true         # Publicar trayectoria real recorrida
    actual_path_len: 4000             # Longitud máxima de la trayectoria guardada
    actual_path_frame: "map"          # Frame para publicar la ruta real
    
    # --- Control por Joystick ---
    joy_topic: "/joy"
    r1_button_index: 5                # PS4/PS5: R1 para toggle autonomía
    x_button_index: 0                 # PS4/PS5: X para desactivar autonomía
    autonomous_start: false           # Iniciar con autonomía desactivada (activar con R1)
